font_family      JetBrains Mono Nerd Font
font_size        9.0
include nord.conf

cursor_blink_interval 0.5
cursor_stop_blinking_after 0
cursor_shape block
shell_integration no-cursor

window_title_template kitty
dynamic_background_opacity yes
hide_window_decorations yes
window_padding_width 0
window_padding_height 0

background_opacity 0.9
set_background_opacity 1

scrollback_lines 10000

middle_click_paste yes
enable_kitty_graphics yes
enable_audio_bell no
