# ============================
#  WINDOW DECORATION SETTINGS
# ============================
decoration {
    # Corner rounding
    rounding = 10                        # Radius of rounded corners (in layout pixels)
    rounding_power = 2.0                # Curve smoothness (2.0=circle, 4.0=squircle, 2.0-10.0)

    # Window opacity
    active_opacity = 1.0             # Active window opacity [0.0-1.0]
    inactive_opacity = 0.8              # Inactive window opacity [0.0-1.0]
    fullscreen_opacity = 1.0            # Fullscreen window opacity [0.0-1.0]

                # Dimming efesfects
    dim_inactive = false                # Enable dimming of inactive windows
    dim_strength = 0.5                  # Dimming strength [0.0-1.0]
    dim_special = 0.6                   # Dimming for special workspaces [0.0-1.0]
    dim_around = 0.4                    # Dimming for dimaround rule [0.0-1.0]

    # Advanced
    screen_shader =                     # Path to custom screen shader (leave empty)
    border_part_of_window = true         # Include border as part of window geometry
}
