general {
    lock_cmd = pidof hyprlock || hyprlock       

    on_lock_cmd = systemctl --user stop idle-inhibit.target  
    on_unlock_cmd = systemctl --user start idle-inhibit.target

    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = hyprctl dispatch dpms on 

    ignore_dbus_inhibit = false        
    ignore_systemd_inhibit = false    
    ignore_wayland_inhibit = false   
    inhibit_sleep = 2               
}

listener {
    timeout = 300                  
    on-timeout = brightnessctl -s set 5%
    on-resume = brightnessctl -r  
    ignore_inhibit = false      
}

listener {
    timeout = 450                     
    on-timeout = hyprctl dispatch dpms off && loginctl lock-session
    on-resume = hyprctl dispatch dpms on
    ignore_inhibit = true          
}

listener {
    timeout = 600                
    on-timeout = systemctl suspend
}
