general {
    hide_cursor = true
        ignore_empty_input = false
        immediate_render = false
        text_trim = true
        fractional_scaling = 2
        screencopy_mode = 0
        fail_timeout = 3
}

background {
    monitor = eDP-1
        path = ~/.wallpapers/hyprlock/wallpaperlock.png
        color = rgba(0, 0, 0, 1.0)
        blur_passes = 0
        blur_size = 0
        brightness = 0.8
        vibrancy = 0.2
        vibrancy_darkness = 0.2
}


# Date Display
label {
    monitor = eDP-1
        text = cmd[update:1000] echo -e "$(date +"%d %B %Y")"
        color = rgba(216, 222, 233, 0.70)
        font_size = 40
        font_family = JetBrains Mono Nerd Font
        position = -65, -300
        halign = right
        valign = top
}

label {
    monitor = eDP-1
        text = cmd[update:1000] echo -e "$(date +"%A")"
        color = rgba(216, 222, 233, 0.70)
        font_size = 40
        font_family = JetBrains Mono Nerd Font
        position = -65, -375
        halign = right
        valign = top
}

# Time Display
label {
    monitor = eDP-1
        text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
        color = rgba(216, 222, 233, 0.70)
        font_size = 200
        font_family = JetBrains Mono Nerd Font
        position = -60, 0
        halign = right
        valign = top
}

input-field {
    monitor = eDP-1
        size = 270, 70
        outline_thickness = 1
        dots_size = 0.2
        dots_spacing = 0.3
        dots_center = true
        outer_color = rgba(0, 0, 0, 0)
        inner_color = rgba(100, 114, 125, 0.4)
        font_color = rgb(200, 200, 200)
        fade_on_empty = true
        font_family = JetBrains Mono Nerd Font
        placeholder_text = <i><span foreground="##b48ead"></span></i>
        hide_input = false
        check_color	= rgba(255, 0, 0, 1.0)
        position = 0, 200
        halign = center
        valign = bottom
}

# Battery status
label {
    monitor = eDP-1
        text = cmd[update:1000] echo -e "$(bash ~/.scripts/hyprlock/batteryStatus.sh)"
        color = rgba(216, 222, 233, 0.70)
        font_size = 18
        font_family = JetBrains Mono Nerd Font
        position = 10, -5
        halign = left
        valign = top
}
